# -*- coding: utf-8 -*-
"""Artimis II

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXIQsvdMrFfrX4TSfMxTGUL_1bIyXwC3
"""

import math
import numpy as np

"""#Gravitational Force"""

#Gravitational Force of E
G = 6.67408 * 10**-20 #km^3 kg^-1 s^-2
M = 5.972 * 10**24 #kg #earth
m = 7.34767309 * 10**22 #kg #moon
r = np.linspace(7000, 382000, 3000) #radius values km from 1 to 300k
F_g = G*M / r**2
U_earth = -G*M/r

moon_avg = 384000 #km

#Moon gravity
F_g_moon = G*m/(moon_avg - r)**2
U_moon = -G*m/(moon_avg - r)

accel_moon = F_g_moon / m
accel_earth = F_g / M

import matplotlib.pyplot as plt

#The Force of Gravity resprestned by a log sacale on the moon as it would be from its radius from 1 km to 300k km
plt.plot(r, F_g)
plt.plot(r,F_g_moon)
plt.yscale('log')
plt.grid(True)
#plt.ylim(float(10**15),float(10**30))
plt.xlabel('radius (km)')
plt.ylabel('Force (N)')
plt.title('Gravitational Force of Earth on the Moon')
plt.show()

#The Force of Gravity resprestned by a log sacale on the moon as it would be from its radius from 1 km to 300k km
plt.plot(r, accel_earth)
plt.plot(r,accel_moon)
#plt.yscale('log')
plt.grid(True)
#plt.ylim(float(10**15),float(10**30))
plt.xlabel('radius (km)')
plt.ylabel('Force (N)')
plt.title('Gravitational Force of Earth on the Moon')
plt.show()

hills = moon_avg * (m / (3 * M))**(1/3)
print(hills)

hills_left = moon_avg - hills
hills_right = moon_avg + hills

xlim_min = hills_left - 100000

# The Force of Gravity represented by a log scale as an object travels from Earth towards the Moon
fig, ax = plt.subplots(figsize = (10,6))
plt.plot(r, F_g, label = 'Force from Earth', color = 'green')
plt.plot(r,F_g_moon, label = 'Force from Moon')


#plt.axvline(moon_avg - hills, linestyle = '--', color='red', label='Moon Hill Sphere Inner Boundary')

plt.yscale('log')
plt.xlabel('Distance from Earth (km)')
plt.ylabel('Force (kN)')
plt.title('Gravitational Force as an Object Approaches the Moon')
plt.grid(True)

# Set xlim to ensure the plot covers the full range of 'r'
plt.xlim(r.min(), r.max())

plt.legend()
plt.show()

hills_plot_idx = np.argmin(np.abs(F_g_moon - F_g))
print(f"The index where forces are approximately equal: {hills_plot_idx}")
print(f"Distance from Earth at this point: {r[hills_plot_idx]:.2f} km")

hills_plot_idx_value = np.abs(r[hills_plot_idx] - moon_avg)
Difference_hills = np.abs(hills_plot_idx_value - hills)
print(Difference_hills)

plt.plot(r, accel_earth)
plt.plot(r, accel_moon)
plt.yscale('log')
plt.grid(True)
#plt.xlim(150000 ,250000)
plt.xlabel('radius (km)')
plt.ylabel('Acceleration (km/s^2)')
plt.title('Gravitational Force of Earth on the Moon')
plt.grid(True)
plt.show()

"""#Exit Velocity"""

r_earth = 6378*1000 #m
v_exit = np.sqrt(2*G*M / r_earth) / 1000

!pip install astroquery

"""#Artemis II"""

from astroquery.jplhorizons import Horizons
from astropy.time import Time

time_start = '2026-04-02T01:59:32'
time_end = '2026-04-10T23:53:13'

Artemis_II = Horizons(id='-1024', location = '@399' , epochs={'start': time_start, 'stop': time_end, 'step': '15m'})
ArtemisII_Eph = Artemis_II.ephemerides()

print(ArtemisII_Eph)

from google.colab import data_table
data_table.enable_dataframe_formatter()

print(ArtemisII_Eph.columns)

RA_1 = ArtemisII_Eph['RA'].value
DEC_1 = ArtemisII_Eph['DEC'].value
r_art = ArtemisII_Eph['delta'].value

#Convert to cartesian coordinates

x_art =np.cos(np.radians(RA_1)) * np.cos(np.radians(DEC_1)) * r_art
y_art = np.cos(np.radians(DEC_1)) * r_art * np.sin(np.radians(RA_1))
z_art = np.sin(np.radians(DEC_1)) * r_art

from mpl_toolkits.mplot3d import Axes3D

Moon = Horizons(id='301', location = '@399' , epochs={'start': time_start, 'stop': time_end, 'step': '15m'})

Moon_Eph = Moon.ephemerides()

Moon_RA = Moon_Eph['RA'].value
Moon_DEC = Moon_Eph['DEC'].value
Moon_r = Moon_Eph['delta'].value

#moon cartesian

x_moon = np.cos(np.radians(Moon_RA)) * np.cos(np.radians(Moon_DEC)) * Moon_r
y_moon = np.cos(np.radians(Moon_DEC)) * Moon_r * np.sin(np.radians(Moon_RA))
z_moon = np.sin(np.radians(Moon_DEC)) * Moon_r

fig = plt.figure(figsize=(15, 12))
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('x (AU)')
ax.set_ylabel('y (AU) ')
ax.set_zlabel('z (AU)') # Changed label to 'delta (AU)'
ax.set_title('Artemis II Trajectory in 3D (Geocentric)')


Art_Plot = ax.plot([], [], [], label='Artemis II Trajectory', color='blue', lw=2)
ax.scatter(0, 0 ,0, color='Green', s=100, label='Earth')
Moon_Plot = ax.plot([],[],[], label='Moon Trajectory', color='red', lw=2)
ax.legend()


min_x = min(x_art.min(), x_moon.min())
max_x = max(x_art.max(), x_moon.max())
min_y = min(y_art.min(), y_moon.min())
max_y = max(y_art.max(), y_moon.max())
min_z = min(z_art.min(), z_moon.min())
max_z = max(z_art.max(), z_moon.max())

ax.set_xlim(min_x, max_x)
ax.set_ylim(min_y, max_y)
ax.set_zlim(min_z, max_z)

import matplotlib.animation as animation
import imageio_ffmpeg
import matplotlib.patches as patches

art_times = Time(ArtemisII_Eph['datetime_jd'].value, format ='jd').iso
moon_times = Time(Moon_Eph['datetime_jd'].value, format ='jd').iso

art_title = ax.set_title(f'Artimis II: {art_times[0][:10]}')

def init_animation():
    Art_Plot[0].set_data([], [])
    Art_Plot[0].set_3d_properties([])
    Moon_Plot[0].set_data([], [])
    Moon_Plot[0].set_3d_properties([])
    art_title.set_text('')
    return Art_Plot[0], Moon_Plot[0], art_title

def update(frame):
    # Access global data arrays directly for slicing. Use frame+1 to include the current frame.
    current_RA_1 = x_art[:frame+1]
    current_DEC_1 = y_art[:frame+1]
    current_r_art = z_art[:frame+1]
    current_Moon_RA = x_moon[:frame+1]
    current_DEC_moon = y_moon[:frame+1]
    current_Moon_r = z_moon[:frame+1]
    Art_Plot[0].set_data_3d(current_RA_1, current_DEC_1, current_r_art)
    Moon_Plot[0].set_data_3d(current_Moon_RA, current_DEC_moon, current_Moon_r)
    art_title.set_text(f'Artemis II: {art_times[frame][:10]}')
    return Art_Plot[0], Moon_Plot[0], art_title

# Calls the update function and makes an animation called 'ani'

ani = animation.FuncAnimation(
    fig=fig,
    func=update,
    frames=len(RA_1),
    interval=50,
    init_func=init_animation,
    blit=True
)

#ani.save(filename="art.mp4", writer="ffmpeg")

"""#Orbiting Earth"""

m_art = 2.61*10**6 #kg
F_thrust = 39.1*10**6 #Newtons



art_acel =  F_thrust / m_art
print("Initial Acceleration:",art_acel,'m/s^2')

print(x_art[0], y_art[0], z_art[0])

#The initial conditions from the data are the final conditions of the launch

#converting to km

AU_km = 1.496 * 10**8

x_art_km = x_art * AU_km
y_art_km = y_art * AU_km
z_art_km = z_art * AU_km

print(x_art_km[0],y_art_km[0],z_art_km[0])

#185km orbit

print(r_art[0]*AU_km)

time_end_short = '2026-04-02T02:05:00'

Artemis_II_short = Horizons(id='-1024', location = '@399' , epochs={'start': time_start, 'stop': time_end_short, 'step': '15m'})
ArtemisII_Eph_short = Artemis_II_short.ephemerides()

Art_vectors = Artemis_II_short.vectors()

#art_vx = Art_vectors['vx'].data
#art_vy = Art_vectors['vy'].data
#art_vz = Art_vectors['vz'].data

#art_rx = Art_vectors['x'].data
#art_ry = Art_vectors['y'].data
#art_rz = Art_vectors['z'].data

#Artermis_II_velocity_mag = np.sqrt(art_vx**2 + art_vy**2 + art_vz**2) * AU_km
#Artermis_II_position_mag = np.sqrt(art_rx **2 + art_ry**2 + art_rz**2) * AU_km

#print(Artermis_II_velocity_mag)
#print(Artermis_II_position_mag)

Art_velo = Artemis_II.vectors()

art_vx = Art_velo['vx'].data
art_vy = Art_velo['vy'].data
art_vz = Art_velo['vz'].data

art_rx = Art_velo['x'].data
art_ry = Art_velo['y'].data
art_rz = Art_velo['z'].data

Artermis_II_velocity_mag = np.sqrt(art_vx**2 + art_vy**2 + art_vz**2) * AU_km * (1/86400)
Artermis_II_position_mag = np.sqrt(art_rx **2 + art_ry**2 + art_rz**2) * AU_km

times = Art_velo['datetime_jd'].data
t0 = times[0]

elapsed_days = (times - t0)

t = Time(times, format='jd', scale='utc')
t_dates = t.to_value('iso','date')

moon_vec = Moon.vectors()

moon_rx = moon_vec['x'].data
moon_ry = moon_vec['y'].data
moon_rz = moon_vec['z'].data

r_moon_from_craft = np.sqrt((art_rx - moon_rx)**2 +
                             (art_ry - moon_ry)**2 +
                             (art_rz - moon_rz)**2) * AU_km

flyby_idx = np.argmin(r_moon_from_craft)
print(flyby_idx)

flyby_idx = np.argmin(r_moon_from_craft)
print(flyby_idx)

print(r_moon_from_craft[flyby_idx])

fly_by = Artermis_II_position_mag[flyby_idx]

moon_hills_left = fly_by - hills
moon_hills_right = fly_by + hills

plt.figure(figsize=(15,10))
ax = plt.gca()
sc = plt.scatter(Artermis_II_position_mag, Artermis_II_velocity_mag, c=elapsed_days, cmap='plasma', s=8)
plt.colorbar(sc, label='Days')
ax.axvspan(moon_hills_left, moon_hills_right, color='red', alpha=0.1, label='Moon Sphere of Influence')
plt.xlabel('Position (km)')
plt.ylabel('Velocity (km/s)')
plt.title('Artemis II Velocity Relative to Earth ')
ax.annotate("Lunar Flyby", xy=(fly_by, .8), textcoords="offset points", xytext=(2, 2), ha='center')
plt.grid(True)
plt.legend(loc = 'lower left')
plt.show()

moon_vec = Moon.vectors()

moon_rx = moon_vec['x'].data
moon_ry = moon_vec['y'].data
moon_rz = moon_vec['z'].data

r_moon_from_craft = np.sqrt((art_rx - moon_rx)**2 +
                             (art_ry - moon_ry)**2 +
                             (art_rz - moon_rz)**2) * AU_km

flyby_idx = np.argmin(r_moon_from_craft)
print(flyby_idx)

print(r_moon_from_craft[flyby_idx])

print(elapsed_days[flyby_idx])

fly_by = Artermis_II_position_mag[flyby_idx]

print(Artermis_II_position_mag[flyby_idx])

plt.figure(figsize=(10,6))
ax = plt.gca()
plt.plot(elapsed_days, Artermis_II_velocity_mag)
#ax.axvspan(0, 1, color='red', alpha=0.1, label='Moon Sphere of Influence')
plt.xlabel('Elapsed Days')
plt.ylabel('Velocity (km/s)')
plt.title('Artemis II Velocity v Days Traveled')
plt.xticks(np.arange(elapsed_days.min(),elapsed_days.max(), step = 1))
plt.grid(True)
plt.ylim(bottom=0)
plt.show()